### ISSUE TITLE
TODO Before Alpha Testing

### ISSUE THREAD

**Issue by alothmanmoe** [NerdHubMC/Simple-Storage-Systems#1]
My checklist that needs to be done so that I can release an alpha at least.

- [x] Finish the caching system for all the drives to speed up terminal item load times instead of rereading each cell's nbt data every time.
- [x] Implement extraction from the system
- [x] Implement multiparts so that the terminal/any other components I decide to add will sit flush with the wireless points.
- [x] Possibly remodel my terminal
- [x] Make the system actually use power now for storing/taking out items/in general
- [x] Add in circuit items
- [x] Rewrite component linking system to make it better and have it work correctly.
- [x] Create recipes for components so the mod is actually usable
- [x] Get a proper texture for my linker item
~- [ ] Make controller gui display connected components~
- [x] Rely on AbusedLib, move all util classes to there.

- [x] LOTS of code cleanup

**Comment by alothmanmoe** [comment]
Completed, check #2
