### ISSUE TITLE
TODO Before Curse Alpha Release

### ISSUE THREAD

**Issue by alothmanmoe** [NerdHubMC/Simple-Storage-Systems#2]
- [ ] Make controller gui display connected components 
- [ ] Add import/export blocks
- [ ] Fix any bugs during private testing
- [ ] Terminal Sorting Options
- [ ] Make search bar actually search
